allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@nerima-games/mc-physics@0.1.0 || 0.1.7'
  - '@nerima-games/mc-kernel@0.2.4 || 0.2.5 || 0.2.7 || 0.2.8 || 0.2.9 || 0.2.14 || 0.2.15 || 0.2.16'
  - '@nerima-games/mc-save@0.1.0'
  - '@nerima-games/mc-worldgen@0.1.1 || 0.1.14'
  - '@nerima-games/mc-noise@0.2.0'
overrides:
  '@nerima-games/mc-kernel': link:../mc-kernel
