/**
 * Published crafting data backed by mc-kernel's closed item vocabulary.
 *
 * Matching and inventory mutation stay in `recipe.ts` and `crafting.ts`; this
 * module owns only the vanilla rows that this simulation can represent.
 */
import {
  shapedRecipe,
  shapelessRecipe,
  type RecipeTable,
} from './recipe.js'
import { itemStack } from './inventory.js'

export const STARTER_RECIPES: RecipeTable = [
  shapelessRecipe('mc-sim:bone-meal', ['bone'], itemStack('bone_meal', 3)),
  shapelessRecipe('mc-sim:oak-planks', ['oak_log'], itemStack('oak_planks', 4)),
  shapedRecipe('mc-sim:stick', ['P', 'P'], { P: 'oak_planks' }, itemStack('stick', 4)),
  shapedRecipe(
    'mc-sim:crafting-table',
    ['PP', 'PP'],
    { P: 'oak_planks' },
    itemStack('crafting_table', 1),
  ),
  shapedRecipe(
    'mc-sim:furnace',
    ['CCC', 'C C', 'CCC'],
    { C: 'cobblestone' },
    itemStack('furnace', 1),
  ),
  shapedRecipe(
    'mc-sim:chest',
    ['PPP', 'P P', 'PPP'],
    { P: 'oak_planks' },
    itemStack('chest', 1),
  ),
  shapedRecipe('mc-sim:torch', ['C', 'S'], { C: 'coal', S: 'stick' }, itemStack('torch', 4)),
  shapedRecipe(
    'mc-sim:bucket',
    ['I I', ' I '],
    { I: 'iron_ingot' },
    itemStack('bucket', 1),
  ),
  shapedRecipe(
    'mc-sim:bow',
    [' ST', 'S T', ' ST'],
    { S: 'stick', T: 'string' },
    itemStack('bow', 1),
  ),
  shapedRecipe('mc-sim:glowstone', ['DD', 'DD'], { D: 'glowstone_dust' }, itemStack('glowstone', 1)),
  shapedRecipe(
    'mc-sim:flint-and-steel',
    ['I ', ' F'],
    { I: 'iron_ingot', F: 'flint' },
    itemStack('flint_and_steel', 1),
  ),
  shapelessRecipe(
    'mc-sim:fire-charge',
    ['gunpowder', 'blaze_powder', 'coal'],
    itemStack('fire_charge', 3),
  ),
  shapelessRecipe(
    'mc-sim:eye-of-ender',
    ['ender_pearl', 'blaze_powder'],
    itemStack('eye_of_ender', 1),
  ),
  shapedRecipe(
    'mc-sim:coal-block',
    ['CCC', 'CCC', 'CCC'],
    { C: 'coal' },
    itemStack('coal_block', 1),
  ),
  shapelessRecipe('mc-sim:coal-from-block', ['coal_block'], itemStack('coal', 9)),
  shapedRecipe(
    'mc-sim:iron-block',
    ['III', 'III', 'III'],
    { I: 'iron_ingot' },
    itemStack('iron_block', 1),
  ),
  shapelessRecipe('mc-sim:iron-from-block', ['iron_block'], itemStack('iron_ingot', 9)),
  shapedRecipe(
    'mc-sim:diamond-block',
    ['DDD', 'DDD', 'DDD'],
    { D: 'diamond' },
    itemStack('diamond_block', 1),
  ),
  shapelessRecipe('mc-sim:diamond-from-block', ['diamond_block'], itemStack('diamond', 9)),
  shapedRecipe(
    'mc-sim:redstone-block',
    ['RRR', 'RRR', 'RRR'],
    { R: 'redstone_dust' },
    itemStack('redstone_block', 1),
  ),
  shapelessRecipe('mc-sim:redstone-from-block', ['redstone_block'], itemStack('redstone_dust', 9)),
  shapedRecipe(
    'mc-sim:lapis-block',
    ['LLL', 'LLL', 'LLL'],
    { L: 'lapis_lazuli' },
    itemStack('lapis_block', 1),
  ),
  shapelessRecipe('mc-sim:lapis-from-block', ['lapis_block'], itemStack('lapis_lazuli', 9)),
  shapedRecipe(
    'mc-sim:emerald-block',
    ['EEE', 'EEE', 'EEE'],
    { E: 'emerald' },
    itemStack('emerald_block', 1),
  ),
  shapelessRecipe('mc-sim:emerald-from-block', ['emerald_block'], itemStack('emerald', 9)),
  shapedRecipe(
    'mc-sim:amethyst-block',
    ['AA', 'AA'],
    { A: 'amethyst_shard' },
    itemStack('amethyst_block', 1),
  ),
  shapelessRecipe('mc-sim:amethyst-from-block', ['amethyst_block'], itemStack('amethyst_shard', 4)),
  shapedRecipe('mc-sim:sandstone', ['SS', 'SS'], { S: 'sand' }, itemStack('sandstone', 1)),
  shapedRecipe(
    'mc-sim:redstone-torch',
    ['R', 'S'],
    { R: 'redstone_dust', S: 'stick' },
    itemStack('redstone_torch', 1),
  ),
  shapedRecipe(
    'mc-sim:lever',
    ['S', 'C'],
    { S: 'stick', C: 'cobblestone' },
    itemStack('lever', 1),
  ),
  shapedRecipe('mc-sim:stone-button', ['C'], { C: 'stone' }, itemStack('stone_button', 1)),
  shapedRecipe(
    'mc-sim:repeater',
    ['T T', ' R ', 'CCC'],
    { T: 'redstone_torch', R: 'redstone_dust', C: 'stone' },
    itemStack('repeater', 1),
  ),
  shapedRecipe(
    'mc-sim:redstone-lamp',
    [' R ', 'RGR', ' R '],
    { R: 'redstone_dust', G: 'glowstone' },
    itemStack('redstone_lamp', 1),
  ),
  shapedRecipe(
    'mc-sim:piston',
    ['PPP', 'CIC', 'CRC'],
    { P: 'oak_planks', C: 'cobblestone', I: 'iron_ingot', R: 'redstone_dust' },
    itemStack('piston', 1),
  ),
  shapedRecipe(
    'mc-sim:dispenser',
    ['CCC', 'CBC', 'CRC'],
    { C: 'cobblestone', B: 'bow', R: 'redstone_dust' },
    itemStack('dispenser', 1),
  ),
  shapedRecipe(
    'mc-sim:dropper',
    ['CCC', 'C C', 'CRC'],
    { C: 'cobblestone', R: 'redstone_dust' },
    itemStack('dropper', 1),
  ),
  shapedRecipe(
    'mc-sim:hopper',
    ['I I', 'ICI', ' I '],
    { I: 'iron_ingot', C: 'chest' },
    itemStack('hopper', 1),
  ),
  shapedRecipe(
    'mc-sim:end-stone-bricks',
    ['EE', 'EE'],
    { E: 'end_stone' },
    itemStack('end_stone_bricks', 4),
  ),
  shapedRecipe(
    'mc-sim:end-crystal',
    ['GGG', 'GHG', 'GEG'],
    { G: 'glass', H: 'ghast_tear', E: 'eye_of_ender' },
    itemStack('end_crystal', 1),
  ),
  shapedRecipe(
    'mc-sim:ender-chest',
    ['OOO', 'OEO', 'OOO'],
    { O: 'obsidian', E: 'eye_of_ender' },
    itemStack('ender_chest', 1),
  ),
  shapedRecipe(
    'mc-sim:purpur-pillar',
    ['P', 'P'],
    { P: 'purpur_block' },
    itemStack('purpur_pillar', 2),
  ),
  shapedRecipe('mc-sim:purpur-slab', ['PPP'], { P: 'purpur_block' }, itemStack('purpur_slab', 6)),
  shapedRecipe(
    'mc-sim:purpur-stairs',
    ['P  ', 'PP ', 'PPP'],
    { P: 'purpur_block' },
    itemStack('purpur_stairs', 4),
  ),
  shapedRecipe(
    'mc-sim:door',
    ['PP', 'PP', 'PP'],
    { P: 'oak_planks' },
    itemStack('door', 3),
  ),
  shapedRecipe(
    'mc-sim:oak-stairs',
    ['P  ', 'PP ', 'PPP'],
    { P: 'oak_planks' },
    itemStack('oak_stairs', 4),
  ),
  shapedRecipe(
    'mc-sim:anvil',
    ['BBB', ' I ', 'III'],
    { B: 'iron_block', I: 'iron_ingot' },
    itemStack('anvil', 1),
  ),
  shapedRecipe(
    'mc-sim:cauldron',
    ['I I', 'I I', 'III'],
    { I: 'iron_ingot' },
    itemStack('cauldron', 1),
  ),
  shapedRecipe(
    'mc-sim:bed',
    ['WWW', 'PPP'],
    { W: 'wool', P: 'oak_planks' },
    itemStack('bed', 1),
  ),
  shapedRecipe(
    'mc-sim:tnt',
    ['GSG', 'SGS', 'GSG'],
    { G: 'gunpowder', S: 'sand' },
    itemStack('tnt', 1),
  ),
  shapedRecipe(
    'mc-sim:ladder',
    ['S S', 'SSS', 'S S'],
    { S: 'stick' },
    itemStack('ladder', 3),
  ),
  shapedRecipe(
    'mc-sim:rail',
    ['I I', 'ISI', 'I I'],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('rail', 16),
  ),
  shapedRecipe(
    'mc-sim:pressure-plate',
    ['PP'],
    { P: 'oak_planks' },
    itemStack('pressure_plate', 1),
  ),
  shapedRecipe('mc-sim:stone-slab', ['CCC'], { C: 'stone' }, itemStack('stone_slab', 6)),
  shapedRecipe(
    'mc-sim:bowl',
    ['P P', ' P '],
    { P: 'oak_planks' },
    itemStack('bowl', 4),
  ),
  shapedRecipe(
    'mc-sim:oak-boat',
    ['P P', 'PPP'],
    { P: 'oak_planks' },
    itemStack('oak_boat', 1),
  ),
  shapedRecipe(
    'mc-sim:minecart',
    ['I I', 'III'],
    { I: 'iron_ingot' },
    itemStack('minecart', 1),
  ),
  shapedRecipe(
    'mc-sim:fishing-rod',
    ['  S', ' ST', 'S T'],
    { S: 'stick', T: 'string' },
    itemStack('fishing_rod', 1),
  ),
  shapedRecipe(
    'mc-sim:shears',
    ['I ', ' I'],
    { I: 'iron_ingot' },
    itemStack('shears', 1),
  ),
  shapedRecipe('mc-sim:wool', ['TT', 'TT'], { T: 'string' }, itemStack('wool', 1)),
  shapelessRecipe('mc-sim:sugar', ['sugar_cane'], itemStack('sugar', 1)),
  shapedRecipe(
    'mc-sim:wooden-pickaxe',
    ['PPP', ' S ', ' S '],
    { P: 'oak_planks', S: 'stick' },
    itemStack('wooden_pickaxe', 1),
  ),
  shapedRecipe(
    'mc-sim:stone-pickaxe',
    ['CCC', ' S ', ' S '],
    { C: 'cobblestone', S: 'stick' },
    itemStack('stone_pickaxe', 1),
  ),
  shapedRecipe(
    'mc-sim:iron-pickaxe',
    ['III', ' S ', ' S '],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('iron_pickaxe', 1),
  ),
  shapedRecipe(
    'mc-sim:diamond-pickaxe',
    ['DDD', ' S ', ' S '],
    { D: 'diamond', S: 'stick' },
    itemStack('diamond_pickaxe', 1),
  ),
  shapedRecipe(
    'mc-sim:wooden-hoe',
    ['PP', ' S', ' S'],
    { P: 'oak_planks', S: 'stick' },
    itemStack('wooden_hoe', 1),
  ),
  shapedRecipe(
    'mc-sim:stone-hoe',
    ['CC', ' S', ' S'],
    { C: 'cobblestone', S: 'stick' },
    itemStack('stone_hoe', 1),
  ),
  shapedRecipe(
    'mc-sim:iron-hoe',
    ['II', ' S', ' S'],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('iron_hoe', 1),
  ),
  shapedRecipe(
    'mc-sim:diamond-hoe',
    ['DD', ' S', ' S'],
    { D: 'diamond', S: 'stick' },
    itemStack('diamond_hoe', 1),
  ),
  shapedRecipe(
    'mc-sim:wooden-sword',
    ['P', 'P', 'S'],
    { P: 'oak_planks', S: 'stick' },
    itemStack('wooden_sword', 1),
  ),
  shapedRecipe(
    'mc-sim:stone-sword',
    ['C', 'C', 'S'],
    { C: 'cobblestone', S: 'stick' },
    itemStack('stone_sword', 1),
  ),
  shapedRecipe(
    'mc-sim:iron-sword',
    ['I', 'I', 'S'],
    { I: 'iron_ingot', S: 'stick' },
    itemStack('iron_sword', 1),
  ),
  shapedRecipe(
    'mc-sim:diamond-sword',
    ['D', 'D', 'S'],
    { D: 'diamond', S: 'stick' },
    itemStack('diamond_sword', 1),
  ),
  shapedRecipe(
    'mc-sim:iron-helmet',
    ['III', 'I I'],
    { I: 'iron_ingot' },
    itemStack('iron_helmet', 1),
  ),
  shapedRecipe(
    'mc-sim:iron-chestplate',
    ['I I', 'III', 'III'],
    { I: 'iron_ingot' },
    itemStack('iron_chestplate', 1),
  ),
  shapedRecipe(
    'mc-sim:iron-leggings',
    ['III', 'I I', 'I I'],
    { I: 'iron_ingot' },
    itemStack('iron_leggings', 1),
  ),
  shapedRecipe(
    'mc-sim:iron-boots',
    ['I I', 'I I'],
    { I: 'iron_ingot' },
    itemStack('iron_boots', 1),
  ),
]
